name: alpha

on:
  push:
    branches:
      - main

jobs:
  prepare_odoo:
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Package Lists
        run: sudo apt-get update

      - name: Fix Broken Packages (if any)
        run: sudo apt-get install -f

      - name: Install PostgreSQL from PostgreSQL Repository
        run: |
          sudo apt-get install -y wget
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main 12" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y postgresql-12 postgresql-server-dev-12

      - name: Install Other System Dependencies
        run: |
          sudo apt-get install -y build-essential fontconfig libfontconfig1-dev libxext-dev libxrender-dev libfreetype6-dev libssl-dev libx11-dev openssl git libldap2-dev libsasl2-dev python3-pillow python3-lxml postgresql-server-dev-12 python3-dev python3-pip python3-setuptools npm nodejs gdebi libxml2-dev python3-wheel python3-venv libxslt1-dev node-less libjpeg-dev
          sudo service postgresql start

      - name: Install wkhtmltopdf
        run: |
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.buster_amd64.deb
          sudo gdebi --n wkhtmltox_0.12.6-1.buster_amd64.deb

      - name: Create Python Virtual Environment
        run: |
          python3 -m venv odoo-venv
          source odoo-venv/bin/activate
          pip install --upgrade pip

      - name: Install Odoo dependencies
        run: |
          source odoo-venv/bin/activate
          pip install -r requirements.txt  # Assuming you have a requirements.txt file with Odoo dependencies

      - name: Configure PostgreSQL
        run: |
          sudo -u postgres createuser --superuser $USER
          createdb -O $USER odoo

      - name: Run Odoo Server
        run: |
          source odoo-venv/bin/activate
          python odoo-bin --addons-path=addons -d odoo
