name: alpha

on:
  push:
    branches:
      - main

jobs:
  prepare_odoo:
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Package Lists
        run: sudo apt-get update

      - name: Fix Broken Packages (if any)
        run: sudo apt-get install -f

      - name: Install PostgreSQL from PostgreSQL Repository
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main 12" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y postgresql-12 postgresql-server-dev-12
          
          # sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          # wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          # sudo apt-get update
          # sudo apt-get install -y postgresql postgresql-server-dev-all
      - name: Install Other System Dependencies
        run: |
          sudo apt-get install -y build-essential fontconfig libfontconfig1-dev libxext-dev libxrender-dev libfreetype6-dev libssl-dev libx11-dev openssl git libldap2-dev libsasl2-dev python3-pillow python3-lxml postgresql postgresql-server-dev-12 python3-dev python3-pip python3-setuptools npm nodejs gdebi libxml2-dev python3-wheel python3-venv libxslt1-dev node-less libjpeg-dev
          sudo service postgresql start
      - name: Install Odoo dependencies
        run: |
          wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
          tar xvf wkhtmltox*.tar.xz
          sudo mv wkhtmltox/bin/wkhtmlto* /usr/bin

          sudo apt update
          sudo apt-get install -y openssl build-essential libssl-dev libxrender-dev git-core libx11-dev libxext-dev libfontconfig1-dev libfreetype6-dev fontconfig 
          sudo apt-get update
          sudo apt upgrade -y
          sudo apt-get install python3.8 python3.8-venv

          python3 -m venv odoo-venv
          source odoo-venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt  # Assuming you have a requirements.txt file with Odoo dependencies
      - name: Start PostgreSQL server
        run: sudo service postgresql start

      - name: Prepare Odoo database
        run: |
          python3 -m venv odoo-venv
          source odoo-venv/bin/activate
      - name: Run Odoo server
        run: |
          source odoo-venv/bin/activate
          sudo cat odoo-bin
