name: Deploy to EC20

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute expect script
        uses: appleboy/ssh-action@v0.1.4
        with:
           host: 13.51.177.145
           username: ubuntu
           key: ${{ secrets.SSH_AWS_KEY }}
           script: |
              bash /opt/odoo15/git-scripts/aws.sh
