name: Deploy to EC200

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2  # Set up Python on the runner
        with:
          python-version: 3  # Replace with the appropriate Python version

      - name: Install Odoo dependencies
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install postgresql build-essential python3-pillow python3-lxml python3-dev python3-pip python3-setuptools npm nodejs git gdebi libldap2-dev libsasl2-dev libxml2-dev python3-wheel python3-venv libxslt1-dev node-less libjpeg-dev -y 
          sudo pg_ctlcluster 12 main start
          sudo apt remove wkhtmltopdf
          sudo apt-get install -y openssl build-essential libssl-dev libxrender-dev git-core libx11-dev libxext-dev libfontconfig1-dev libfreetype6-dev fontconfig
          apt install python3.8-venv
          
          python3 -m venv odoo-venv
          source odoo-venv/bin/activate
          pip3 install wheel
          pip3 install -r requirements.txt  # Assuming you have a requirements.txt file with Odoo dependencies

      - name: Start Odoo server
        run: |
          odoo-bin -c odoo.conf  # Replace with the path to your Odoo configuration file

      - name: Execute expect script
        uses: appleboy/ssh-action@v0.1.4
        with:
           host: 13.51.177.145
           username: ubuntu
           key: ${{ secrets.SSH_AWS_KEY }}
           script: |
              bash /opt/odoo15/git-scripts/aws.sh

