name: Prepare Odoo Environment

on:
  push:
    branches:
      - main

jobs:
  prepare_odoo:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Package Lists
        run: sudo apt-get update

      - name: Fix Broken Packages (if any)
        run: sudo apt-get install -f

      - name: Install PostgreSQL from PostgreSQL Repository
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-server-dev-all

      - name: Install Other System Dependencies
        run: |
          sudo apt-get install -y build-essential fontconfig libfontconfig1-dev libxext-dev libxrender-dev libfreetype6-dev libssl-dev libx11-dev openssl git libldap2-dev

      - name: Install Odoo dependencies
        run: |
          python3 -m venv odoo-venv
          source odoo-venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt  # Assuming you have a requirements.txt file with Odoo dependencies

      - name: Start PostgreSQL server
        run: sudo service postgresql start

      - name: Prepare Odoo database
        run: |
          source odoo-venv/bin/activate
          python odoo-bin -c odoo.conf -d <your_database_name> --without-demo=ALL --stop-after-init

      - name: Run Odoo server
        run: |
          source odoo-venv/bin/activate
          python odoo-bin -c odoo.conf


