name: Odoo Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: 3.9
  ODOO_VERSION: 15.0
  POSTGRESQL_VERSION: 13

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure PostgreSQL
        uses: docker/setup-postgres@v1
        with:
          postgres-version: ${{ env.POSTGRESQL_VERSION }}

      - name: Set up Odoo
        run: |
          wget -O - https://nightly.odoo.com/odoo.key | sudo apt-key add -
          echo "deb http://nightly.odoo.com/${{ env.ODOO_VERSION }}/nightly/deb/ ./" | sudo tee /etc/apt/sources.list.d/odoo.list
          sudo apt-get update
          sudo apt-get install odoo

      - name: Start Odoo server
        run: sudo service odoo start

      - name: Run tests
        run: |
          cd path/to/your/odoo/module
          python -m unittest discover

      - name: Stop Odoo server
        run: sudo service odoo stop
